### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by davidmascharka** [davidmascharka/MyNN#31]
Monolithic issue for unit testing things. We'll construct a list here; comment to add things to it.

- **Mutation**: ensure that operations do not modify their input

**Comment by davidmascharka** [comment]
Ryan pointed out that the initial implementation of batchnorm would mutate the input if the input was a NumPy array. This has been fixed, but points to one of the things we should definitely check for in all our operations.

**Comment by davidmascharka** [comment]
Blocks #42

**Comment by rsokl** [comment]
I started thinking, after our discussion with the uber wrapper: should we start introducing MyNN features directly into a branch on MyGrad, fastidiously adding tests as we go along. Regarding the uber wrapper, were you planning to just copy-paste MyGrad's test utilities here?

I realize that this doesn't exactly align with the current plan of: get MyNN into fighting shape and then start merging. But in the chance that you want to make use of some of MyGrad's utilties/internals/test-utils it would likely be easier to do so from within MyGrad.

**Comment by davidmascharka** [comment]
Hmm that's a good point. Maybe creating a MyNN-merge branch off of MyGrad master makes more sense. For now I copied over the uber wrapper into MyNN but agreed that's not a good path forward. How would you feel about:

- MyNN-merge branch off of MyGrad master which has stable/tested/covered features of MyNN
- Branches off of MyNN-merge with MyNN-merge as the base for migrating features over

Example: I create a `glu` branch off of `mynn-merge` and submit a PR into `mynn-merge` that gets pulled in once coverage is 100% and documentation looks good. Anybody who's a bit adventurous can use the `mynn-merge` as an experimental branch if they like. On merge into master, there should be a clean history in git of each feature that gets migrated.

**Comment by rsokl** [comment]
Yeah I think that is a great approach. And that way you also get the benefit of MyGrad's CI system - instead of writing your own just to tear it down. Plus, this way we can make design decisions as we do test-driven development. Instead of writing tests, then potentially redesign.

I can also begin working on the docs and merge that into `mynn-merge` along the way so that it isn't one heavy lift all at the end.
