### ISSUE TITLE
Add ability to turn bias off for conv layer

### ISSUE THREAD

**Issue by rsokl** [davidmascharka/MyNN#33]
In light of the availability of batchnorm, it would be nice to off the bias term for the conv layer [as we do with dense](https://github.com/davidmascharka/MyNN/blob/b9616b550a2940f5adda6e618e61c377f5660cf1/mynn/layers/dense.py#L37)

**Comment by davidmascharka** [comment]
Bias option added in d2ebdc2d541d64c5c751de83e000cdc70648a867
