### ISSUE TITLE
Unicode variable names

### ISSUE THREAD

**Issue by davidmascharka** [davidmascharka/MyNN#38]
In implementing some of the optimizers, I'm wondering what everyone's thoughts are on using non-ascii unicode variable names. For example, the adadelta implementation currently sits as:

``` python
self.g[idx] = self.rho * self.g[idx] + (1 - self.rho) * grad**2
dx = -np.sqrt(self.dx[idx] + self.eps) / np.sqrt(self.g[idx] + self.eps) * grad
self.dx[idx] = self.rho * self.dx[idx] + (1 - self.rho) * dx**2
```

However, this could easily be written this way to better match the paper:

``` python
self.g[idx] = self.ρ * self.g[idx] + (1 - self.ρ) * grad**2
Δx = -np.sqrt(self.Δx[idx] + self.ɛ) / np.sqrt(self.g[idx] + self.ɛ) * grad
self.Δx[idx] = self.ρ * self.Δx[idx] + (1 - self.ρ) * Δx**2
```

My initial thought: using unicode names can potentially result in some additional clarity. For non-user-facing code, this might be a good thing. We probably ought not have unicode names in function signatures, as some users may have difficulty in typing unicode characters.

**Comment by rsokl** [comment]
I do think that non-ascii unicode characters are useful for instances like the one highlighted here - there really is nothing sophisticated going on, *other than faithfully reproducing the equations from a paper*, and the code is effectively self contained.

I also checked to verify that these characters are handled gracefully in Jupyter/jedi, e.g. they can be fetched by tab-completion.

**Comment by davidmascharka** [comment]
Cool, I agree; the unicode names can be helpful and for internal-only code there certainly shouldn't be any problems. We just need people to switch to writing unicode everywhere :sunglasses:
